### ISSUE TITLE
Event merge for calendar preview panel on mail.google.com too

### ISSUE THREAD

**Issue by balintfodor** [imightbeamy/gcal-multical-event-merge#75]
This fantastic extension should work on Gmail's right panel for the calendar preview too.

**Comment by balintfodor** [comment]
Just saw that it's in https://github.com/imightbeamy/gcal-multical-event-merge/commit/4d99e838736aed0914fb45b49844cec8a2b500ee 👏

**Comment by kfarwell** [comment]
4d99e83 seems not to implement this fully. I'm still seeing duplicate events even after adding mail.google.com includes/permissions in events.user.js and manifest.json. Did you get this working, @balintfodor?

**Comment by balintfodor** [comment]
I don't have much experience with chrome extension development, what I've done is clone master (https://github.com/imightbeamy/gcal-multical-event-merge/commit/4d99e838736aed0914fb45b49844cec8a2b500ee), call `build`, switch to "developer mode" in `chrome://extensions` then drop the built zip in. After refreshing Gmail it was there. 
I'm guessing that there's no need to add `mail.google.com` because the Gmail panel syncs the view from `calendar.google.com`, but again, I'm very inexperienced in this.
Don't know if it's useful info, I'm on Chrome `Version 74.0.3729.169 (Official Build) (64-bit)`.

**Comment by kfarwell** [comment]
Weird. I did the same thing. I am using G Suite in Brave 74.0.3729.108, maybe there is some difference.

**Comment by imightbeamy** [comment]
Hi all, I implemented this back in December but apparently forgot to update the extension in the chrome store 😅 What a shame! Anyway, it's been updated now and this should start working in the gmail panel.

**Comment by kfarwell** [comment]
I've updated from 4d99e83 to 2.2.0 on the Chrome store and I'm still seeing duplicates in the Gmail panel.
